In [3]:
            ##QUESTIONS
#1. Display Top 5 Rows of The Dataset
#2. Check the Last 3 Rows of The Dataset
#3. Find Shape of Our Dataset (Number of Rows & Number of Columns)
#4. Get Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column 
 #  And  Memory Requirement
#5. Get Overall Statistics About The Dataframe OR Get the Descriptive Statistics about Google Play Store
#6. Obtain Total Number of App Titles Contain Astrology
#7. Find Average App Rating
#8.  Find Total Number of Unique Category
#9. Which Category Getting The Highest Average Rating?
#10. Find Total Number of App having 5 Star Rating
#11. Find Average Value of Reviews
#12. Find Total Number of Free and Paid Apps
#13.  Which App Has Maximum Reviews?
#14. Display Top 5 Apps Having Highest Reviews
#15. Find Average Rating of Free and Paid Apps
#16. Display Top  5 Apps Having Maximum Installs

In [60]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.expand_frame_repr", False)

In [62]:
#Read the Records from Google Play Store Related CSV File
import pandas as pd
import numpy as np
df=pd.read_csv("D:\\PANDAS\\Google Play Store.csv")
print(df)

                                                     App             Category  Rating Reviews                Size     Installs  Type Price Content Rating                     Genres      Last Updated         Current Ver         Android Ver
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN     4.1     159                 19M      10,000+  Free     0       Everyone               Art & Design   January 7, 2018               1.0.0        4.0.3 and up
1                                    Coloring book moana       ART_AND_DESIGN     3.9     967                 14M     500,000+  Free     0       Everyone  Art & Design;Pretend Play  January 15, 2018               2.0.0        4.0.3 and up
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN     4.7   87510                8.7M   5,000,000+  Free     0       Everyone               Art & Design    August 1, 2018               1.2.4        4.0.3 and up
3                                  Sketch - Draw & Paint       ART_AND_DESIGN     4.5  215644                 25M  50,000,000+  Free     0           Teen               Art & Design      June 8, 2018  Varies with device          4.2 and up
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN     4.3     967                2.8M     100,000+  Free     0       Everyone    Art & Design;Creativity     June 20, 2018                 1.1          4.4 and up
...                                                  ...                  ...     ...     ...                 ...          ...   ...   ...            ...                        ...               ...                 ...                 ...
10836                                   Sya9a Maroc - FR               FAMILY     4.5      38                 53M       5,000+  Free     0       Everyone                  Education     July 25, 2017                1.48          4.1 and up
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY     5.0       4                3.6M         100+  Free     0       Everyone                  Education      July 6, 2018                 1.0          4.1 and up
10838                             Parkinson Exercices FR              MEDICAL     NaN       3                9.5M       1,000+  Free     0       Everyone                    Medical  January 20, 2017                 1.0          2.2 and up
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE     4.5     114  Varies with device       1,000+  Free     0     Mature 17+          Books & Reference  January 19, 2015  Varies with device  Varies with device
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE     4.5  398307                 19M  10,000,000+  Free     0       Everyone                  Lifestyle     July 25, 2018  Varies with device  Varies with device

[10841 rows x 13 columns]

In [63]:
#Sample-1. Find Total Number Apps in Google Play Store
df.shape

(10841, 13)

In [64]:
print("Find Total Number Apps in Google Play Store=",df.shape[0])

Find Total Number Apps in Google Play Store= 10841

In [65]:
print("Find Total Number of column Apps in Google Play Store=",df.shape[1])

Find Total Number of column Apps in Google Play Store= 13

In [66]:
#1. Display Top 5 Rows of The Dataset
df.head(5) # OR df.head()

                                                 App        Category  Rating Reviews  Size     Installs  Type Price Content Rating                     Genres      Last Updated         Current Ver   Android Ver
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1     159   19M      10,000+  Free     0       Everyone               Art & Design   January 7, 2018               1.0.0  4.0.3 and up
1                                Coloring book moana  ART_AND_DESIGN     3.9     967   14M     500,000+  Free     0       Everyone  Art & Design;Pretend Play  January 15, 2018               2.0.0  4.0.3 and up
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   87510  8.7M   5,000,000+  Free     0       Everyone               Art & Design    August 1, 2018               1.2.4  4.0.3 and up
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5  215644   25M  50,000,000+  Free     0           Teen               Art & Design      June 8, 2018  Varies with device    4.2 and up
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3     967  2.8M     100,000+  Free     0       Everyone    Art & Design;Creativity     June 20, 2018                 1.1    4.4 and up

In [67]:
#2. Check the Last 3 Rows of The Dataset
df.tail(3)

                                                 App             Category  Rating Reviews                Size     Installs  Type Price Content Rating             Genres      Last Updated         Current Ver         Android Ver
10838                         Parkinson Exercices FR              MEDICAL     NaN       3                9.5M       1,000+  Free     0       Everyone            Medical  January 20, 2017                 1.0          2.2 and up
10839                  The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE     4.5     114  Varies with device       1,000+  Free     0     Mature 17+  Books & Reference  January 19, 2015  Varies with device  Varies with device
10840  iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE     4.5  398307                 19M  10,000,000+  Free     0       Everyone          Lifestyle     July 25, 2018  Varies with device  Varies with device

In [68]:
# OR
df[len(df)-3:]

                                                 App             Category  Rating Reviews                Size     Installs  Type Price Content Rating             Genres      Last Updated         Current Ver         Android Ver
10838                         Parkinson Exercices FR              MEDICAL     NaN       3                9.5M       1,000+  Free     0       Everyone            Medical  January 20, 2017                 1.0          2.2 and up
10839                  The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE     4.5     114  Varies with device       1,000+  Free     0     Mature 17+  Books & Reference  January 19, 2015  Varies with device  Varies with device
10840  iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE     4.5  398307                 19M  10,000,000+  Free     0       Everyone          Lifestyle     July 25, 2018  Varies with device  Varies with device

In [69]:
#3. Find Shape of Our Dataset (Number of Rows & Number of Columns)
print("Shape of Google Play Store DataSet=",df.shape)
print("Number of Rows=",df.shape[0])
print("Number of Columns=",df.shape[1])

Shape of Google Play Store DataSet= (10841, 13)
Number of Rows= 10841
Number of Columns= 13

In [70]:
#4. Get Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column 
 #  And  Memory Requirement
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [71]:
#5. Get Overall Statistics About The Dataframe OR
#Get the Descriptive Statistics about Google Play Store
df.describe(include="all")

           App Category       Rating Reviews                Size    Installs   Type  Price Content Rating Genres    Last Updated         Current Ver Android Ver
count    10841    10841  9367.000000   10841               10841       10841  10840  10841          10840  10841           10841               10833       10838
unique    9660       34          NaN    6002                 462          22      3     93              6    120            1378                2832          33
top     ROBLOX   FAMILY          NaN       0  Varies with device  1,000,000+   Free      0       Everyone  Tools  August 3, 2018  Varies with device  4.1 and up
freq         9     1972          NaN     596                1695        1579  10039  10040           8714    842             326                1459        2451
mean       NaN      NaN     4.193338     NaN                 NaN         NaN    NaN    NaN            NaN    NaN             NaN                 NaN         NaN
std        NaN      NaN     0.537431     NaN                 NaN         NaN    NaN    NaN            NaN    NaN             NaN                 NaN         NaN
min        NaN      NaN     1.000000     NaN                 NaN         NaN    NaN    NaN            NaN    NaN             NaN                 NaN         NaN
25%        NaN      NaN     4.000000     NaN                 NaN         NaN    NaN    NaN            NaN    NaN             NaN                 NaN         NaN
50%        NaN      NaN     4.300000     NaN                 NaN         NaN    NaN    NaN            NaN    NaN             NaN                 NaN         NaN
75%        NaN      NaN     4.500000     NaN                 NaN         NaN    NaN    NaN            NaN    NaN             NaN                 NaN         NaN
max        NaN      NaN    19.000000     NaN                 NaN         NaN    NaN    NaN            NaN    NaN             NaN                 NaN         NaN

In [72]:
# 6. Obtain Total Number of App Titles Contain 'Astrology'
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [73]:
df["App"]

0           Photo Editor & Candy Camera & Grid & ScrapBook
1                                      Coloring book moana
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
                               ...
10836                                     Sya9a Maroc - FR
10837                     Fr. Mike Schmitz Audio Teachings
10838                               Parkinson Exercices FR
10839                        The SCP Foundation DB fr nn5n
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 10841, dtype: str

In [74]:
df["App"].str.contains("Astrology")

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840     True
Name: App, Length: 10841, dtype: bool

In [75]:
df[df["App"].str.contains("Astrology")]

                                                     App   Category  Rating Reviews Size     Installs  Type Price Content Rating     Genres   Last Updated         Current Ver         Android Ver
1570   Horoscopes – Daily Zodiac Horoscope and Astrology  LIFESTYLE     4.6  161143  11M  10,000,000+  Free     0   Everyone 10+  Lifestyle  June 25, 2018          5.2.4(881)        4.0.3 and up
1592              သိင်္ Astrology - Min Thein Kha BayDin  LIFESTYLE     4.7    2225  15M     100,000+  Free     0       Everyone  Lifestyle  July 26, 2018               4.2.1        4.0.3 and up
10840      iHoroscope - 2018 Daily Horoscope & Astrology  LIFESTYLE     4.5  398307  19M  10,000,000+  Free     0       Everyone  Lifestyle  July 25, 2018  Varies with device  Varies with device

In [76]:
df[df["App"].str.contains("Astrology")]["App"]

1570     Horoscopes – Daily Zodiac Horoscope and Astrology
1592                သိင်္ Astrology - Min Thein Kha BayDin
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, dtype: str

In [77]:
df[df["App"].str.contains("Astrology",case=False)]["App"]

1570     Horoscopes – Daily Zodiac Horoscope and Astrology
1592                သိင်္ Astrology - Min Thein Kha BayDin
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, dtype: str

In [78]:
print("-----------------------------------------")
print("App Titles Contain 'Astrology'")
print("-----------------------------------------")
for appname in df[df["App"].str.contains("Astrology",case=False)]["App"]:
 print(appname)
print("-----------------------------------------")

-----------------------------------------
App Titles Contain 'Astrology'
-----------------------------------------
Horoscopes – Daily Zodiac Horoscope and Astrology
သိင်္ Astrology - Min Thein Kha BayDin
iHoroscope - 2018 Daily Horoscope & Astrology
-----------------------------------------

In [79]:
#7. Find Average App Rating
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [80]:
df["Rating"]

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10836    4.5
10837    5.0
10838    NaN
10839    4.5
10840    4.5
Name: Rating, Length: 10841, dtype: float64

In [81]:
print("Average App Rating in Google Play Store=",df["Rating"].mean())

Average App Rating in Google Play Store= 4.193338315362443

In [82]:
#8. Find Total Number of Unique Category
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [83]:
df["Category"]

0             ART_AND_DESIGN
1             ART_AND_DESIGN
2             ART_AND_DESIGN
3             ART_AND_DESIGN
4             ART_AND_DESIGN
                ...
10836                 FAMILY
10837                 FAMILY
10838                MEDICAL
10839    BOOKS_AND_REFERENCE
10840              LIFESTYLE
Name: Category, Length: 10841, dtype: str

In [84]:
df["Category"].unique()

<StringArray>
[     'ART_AND_DESIGN',   'AUTO_AND_VEHICLES',              'BEAUTY',
 'BOOKS_AND_REFERENCE',            'BUSINESS',              'COMICS',
       'COMMUNICATION',              'DATING',           'EDUCATION',
       'ENTERTAINMENT',              'EVENTS',             'FINANCE',
      'FOOD_AND_DRINK',  'HEALTH_AND_FITNESS',      'HOUSE_AND_HOME',
  'LIBRARIES_AND_DEMO',           'LIFESTYLE',                'GAME',
              'FAMILY',             'MEDICAL',              'SOCIAL',
            'SHOPPING',         'PHOTOGRAPHY',              'SPORTS',
    'TRAVEL_AND_LOCAL',               'TOOLS',     'PERSONALIZATION',
        'PRODUCTIVITY',           'PARENTING',             'WEATHER',
       'VIDEO_PLAYERS',  'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
                 '1.9']
Length: 34, dtype: str

In [85]:
print("Total Number of Unique Category=",df["Category"].nunique())

Total Number of Unique Category= 34

In [86]:
#Categoryt Names with Total Number of same Category
df["Category"].value_counts()

Category
FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
COMICS                   60
PARENTING                60
BEAUTY                   53
1.9                       1
Name: count, dtype: int64

In [88]:
#App Names with Unique Category
for appname in df["Category"].unique():
 print(appname)

ART_AND_DESIGN
AUTO_AND_VEHICLES
BEAUTY
BOOKS_AND_REFERENCE
BUSINESS
COMICS
COMMUNICATION
DATING
EDUCATION
ENTERTAINMENT
EVENTS
FINANCE
FOOD_AND_DRINK
HEALTH_AND_FITNESS
HOUSE_AND_HOME
LIBRARIES_AND_DEMO
LIFESTYLE
GAME
FAMILY
MEDICAL
SOCIAL
SHOPPING
PHOTOGRAPHY
SPORTS
TRAVEL_AND_LOCAL
TOOLS
PERSONALIZATION
PRODUCTIVITY
PARENTING
WEATHER
VIDEO_PLAYERS
NEWS_AND_MAGAZINES
MAPS_AND_NAVIGATION
1.9

In [89]:
#9. Which Category Getting The Highest Average Rating?
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [94]:
appname=df.groupby("Category")['Rating'].mean().sort_values(ascending=False)
print("Category Getting The Highest Average Rating=",appname)

Category Getting The Highest Average Rating= Category
1.9                    19.000000
EVENTS                  4.435556
EDUCATION               4.389032
ART_AND_DESIGN          4.358065
BOOKS_AND_REFERENCE     4.346067
PERSONALIZATION         4.335987
PARENTING               4.300000
GAME                    4.286326
BEAUTY                  4.278571
HEALTH_AND_FITNESS      4.277104
SHOPPING                4.259664
SOCIAL                  4.255598
WEATHER                 4.244000
SPORTS                  4.223511
PRODUCTIVITY            4.211396
HOUSE_AND_HOME          4.197368
FAMILY                  4.192272
PHOTOGRAPHY             4.192114
AUTO_AND_VEHICLES       4.190411
MEDICAL                 4.189143
LIBRARIES_AND_DEMO      4.178462
FOOD_AND_DRINK          4.166972
COMMUNICATION           4.158537
COMICS                  4.155172
NEWS_AND_MAGAZINES      4.132189
FINANCE                 4.131889
ENTERTAINMENT           4.126174
BUSINESS                4.121452
TRAVEL_AND_LOCAL        4.109292
LIFESTYLE               4.094904
VIDEO_PLAYERS           4.063750
MAPS_AND_NAVIGATION     4.051613
TOOLS                   4.047411
DATING                  3.970769
Name: Rating, dtype: float64

In [95]:
#10. Find Total Number of Apps having 5 Star Rating
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [96]:
df["Rating"]

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10836    4.5
10837    5.0
10838    NaN
10839    4.5
10840    4.5
Name: Rating, Length: 10841, dtype: float64

In [97]:
df["Rating"]==5

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837     True
10838    False
10839    False
10840    False
Name: Rating, Length: 10841, dtype: bool

In [98]:
df[df["Rating"]==5]

                                              App   Category  Rating Reviews  Size Installs  Type Price Content Rating     Genres       Last Updated Current Ver   Android Ver
329                  Hojiboy Tojiboyev Life Hacks     COMICS     5.0      15   37M   1,000+  Free     0       Everyone     Comics      June 26, 2018         2.0  4.0.3 and up
612                 American Girls Mobile Numbers     DATING     5.0       5  4.4M   1,000+  Free     0     Mature 17+     Dating      July 17, 2018         3.0  4.0.3 and up
615                                  Awake Dating     DATING     5.0       2   70M     100+  Free     0     Mature 17+     Dating      July 24, 2018       2.2.9    4.4 and up
633                         Spine- The dating app     DATING     5.0       5  9.3M     500+  Free     0           Teen     Dating      July 14, 2018         4.0  4.0.3 and up
636    Girls Live Talk - Free Text and Video Chat     DATING     5.0       6  5.0M     100+  Free     0     Mature 17+     Dating     August 1, 2018         8.2  4.0.3 and up
...                                           ...        ...     ...     ...   ...      ...   ...   ...            ...        ...                ...         ...           ...
10721                           Mad Dash Fo' Cash       GAME     5.0      14   16M     100+  Free     0       Everyone     Arcade      June 19, 2017        2.5a    4.1 and up
10742                       GKPB FP Online Church  LIFESTYLE     5.0      32  7.9M   1,000+  Free     0       Everyone  Lifestyle  December 31, 2017       0.7.1    4.4 and up
10776                            Monster Ride Pro       GAME     5.0       1   24M      10+  Free     0       Everyone     Racing      March 5, 2018         2.0    2.3 and up
10820                             Fr. Daoud Lamei     FAMILY     5.0      22  8.6M   1,000+  Free     0           Teen  Education      June 27, 2018       3.8.0    4.1 and up
10837            Fr. Mike Schmitz Audio Teachings     FAMILY     5.0       4  3.6M     100+  Free     0       Everyone  Education       July 6, 2018         1.0    4.1 and up

[274 rows x 13 columns]

In [101]:
print("Total Number of Apps having 5 Star Rating=",len(df[df["Rating"]==5]))

Total Number of Apps having 5 Star Rating= 274

In [103]:
#11. Find Average Value of Reviews
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [107]:
#11. Find Average Value of Reviews
df["Reviews"].dtype

In [108]:
df["Reviews"].astype("float")

ValueError: could not convert string to float: '3.0M'

In [109]:
df[df["Reviews"]=='3.0M']

                                           App Category  Rating Reviews    Size Installs Type     Price Content Rating             Genres Last Updated Current Ver Android Ver
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9    19.0    3.0M  1,000+     Free    0  Everyone            NaN  February 11, 2018       1.0.19  4.0 and up         NaN

In [110]:
df["Reviews"]=df["Reviews"].replace("3.0M",3000000.0)

In [111]:
df.loc[10472]

App               Life Made WI-Fi Touchscreen Photo Frame
Category                                              1.9
Rating                                               19.0
Reviews                                         3000000.0
Size                                               1,000+
Installs                                             Free
Type                                                    0
Price                                            Everyone
Content Rating                                        NaN
Genres                                  February 11, 2018
Last Updated                                       1.0.19
Current Ver                                    4.0 and up
Android Ver                                           NaN
Name: 10472, dtype: object

In [114]:
df["Reviews"]=df["Reviews"].astype("float")
df["Reviews"].dtype

dtype('float64')

In [115]:
print("Average Value of Reviews=",df["Reviews"].mean())

Average Value of Reviews= 444388.6535374965

In [116]:
##12. Find Total Number of Free and Paid Apps
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [117]:
df.groupby("Type").size()

Type
0           1
Free    10039
Paid      800
dtype: int64

In [119]:
print("Total Number of Free and Paid Apps")
print(df["Type"].value_counts())
print("------------OR------------------")
print(df.groupby("Type").size())

Total Number of Free and Paid Apps
Type
Free    10039
Paid      800
0           1
Name: count, dtype: int64
------------OR------------------
Type
0           1
Free    10039
Paid      800
dtype: int64

In [120]:
#13. Find which app has Maximum Review
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [121]:
df['Reviews'].max()

np.float64(78158306.0)

In [122]:
df['Reviews'].max()==df['Reviews']

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Reviews, Length: 10841, dtype: bool

In [123]:
df[df['Reviews'].max()==df['Reviews']]

           App Category  Rating     Reviews                Size        Installs  Type Price Content Rating  Genres    Last Updated         Current Ver         Android Ver
2544  Facebook   SOCIAL     4.1  78158306.0  Varies with device  1,000,000,000+  Free     0           Teen  Social  August 3, 2018  Varies with device  Varies with device

In [124]:
df[df['Reviews'].max()==df['Reviews']]["App"].values[0]

'Facebook'

In [125]:
df.iloc[df['Reviews'].sort_values(ascending=False).index[0]]["App"]

'Facebook'

In [126]:
#14#Find the Top 5 App Names having highest Review
df["Reviews"].sort_values(ascending=False)

2544     78158306.0
3943     78128208.0
381      69119316.0
336      69119316.0
3904     69109672.0
            ...
10772           0.0
7346            0.0
5302            0.0
5298            0.0
7386            0.0
Name: Reviews, Length: 10841, dtype: float64

In [ ]:
ind=df["Reviews"].sort_values(ascending=False).head().index

In [144]:
df.iloc[ind]["App"]

2544              Facebook
3943              Facebook
381     WhatsApp Messenger
336     WhatsApp Messenger
3904    WhatsApp Messenger
Name: App, dtype: str

In [145]:
#15.Find Average Rating of Free and Paid Apps
df.groupby("Type")["Rating"].mean()

Type
0       19.000000
Free     4.186203
Paid     4.266615
Name: Rating, dtype: float64

In [146]:
#16. Find Top 5 Apps Having Maximum Installs
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [147]:
df['Installs'].dtype

In [148]:
df['Installs']

0            10,000+
1           500,000+
2         5,000,000+
3        50,000,000+
4           100,000+
            ...
10836         5,000+
10837           100+
10838         1,000+
10839         1,000+
10840    10,000,000+
Name: Installs, Length: 10841, dtype: str

In [149]:
df['Installs']=df['Installs'].astype("float")

ValueError: could not convert string to float: '10,000+'

In [150]:
df[df['Installs']=="Free"]

                                           App Category  Rating    Reviews    Size Installs Type     Price Content Rating             Genres Last Updated Current Ver Android Ver
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9    19.0  3000000.0  1,000+     Free    0  Everyone            NaN  February 11, 2018       1.0.19  4.0 and up         NaN

In [152]:
df['Installs']=df['Installs'].str.replace("Free","0")

In [156]:
df['Installs'].sort_values(ascending=False).head().index

Index([1661, 4039, 385, 3562, 4048], dtype='int64')

In [165]:
df.iloc[df['Installs'].sort_values(ascending=False).head(5).index]["App"].values

<StringArray>
[                         'Temple Run 2',
 'Google Duo - High Quality Video Calls',
                       'Viber Messenger',
                       'Google Calendar',
                               'Dropbox']
Length: 5, dtype: str

In [167]:
print("Top 5 Apps Having Maximum Installs")
for appname in df.iloc[df['Installs'].sort_values(ascending=False).head().index].values:
 print(appname)

Top 5 Apps Having Maximum Installs
['Temple Run 2' 'GAME' 4.3 8118609.0 '62M' '500,000,000+' 'Free' '0'
 'Everyone' 'Action' 'July 5, 2018' '1.49.1' '4.0 and up']
['Google Duo - High Quality Video Calls' 'COMMUNICATION' 4.6 2083237.0
 'Varies with device' '500,000,000+' 'Free' '0' 'Everyone' 'Communication'
 'July 31, 2018' '37.1.206017801.DR37_RC14' '4.4 and up']
['Viber Messenger' 'COMMUNICATION' 4.3 11334973.0 'Varies with device'
 '500,000,000+' 'Free' '0' 'Everyone' 'Communication' 'July 18, 2018'
 'Varies with device' 'Varies with device']
['Google Calendar' 'PRODUCTIVITY' 4.2 858230.0 'Varies with device'
 '500,000,000+' 'Free' '0' 'Everyone' 'Productivity' 'August 6, 2018'
 'Varies with device' 'Varies with device']
['Dropbox' 'PRODUCTIVITY' 4.4 1860844.0 '61M' '500,000,000+' 'Free' '0'
 'Everyone' 'Productivity' 'August 1, 2018' 'Varies with device'
 'Varies with device']